language: node_js
node_js:
- 0.12
notifications:
  email:
    recipients:
    - tates001@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: npm
  email: tates001@gmail.com
  api_key:
    secure: $API_KEY
  on:
    tags: true
    repo: amcmillan01/jsdoc2diagram
script:
- npm install
- npm publish
